# Generated by Django 5.1.3 on 2024-11-28 17:39

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('dentista', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=timezone.now)),
                ('procedimento', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
