# Generated by Django 5.1.3 on 2024-11-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0001_initial"),
        ("procedimentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="dentista",
        ),
        migrations.RemoveField(
            model_name="consulta",
            name="observacoes",
        ),
        migrations.AlterField(
            model_name="consulta",
            name="data_hora",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="paciente",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="procedimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="procedimentos.procedimento",
            ),
        ),
    ]
